// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVVn002iMZuXvq636K7YA1bPKCUrx1acQ',
    appId: '1:65217506040:web:0a3f9d8d3267ffacfba90d',
    messagingSenderId: '65217506040',
    projectId: 'wateriq-cloud',
    authDomain: 'wateriq-cloud.firebaseapp.com',
    storageBucket: 'wateriq-cloud.appspot.com',
    measurementId: 'G-VC4DCB0DJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRtJj5_cpcUNLtuBgKBD9TMGuxIyxBXZ0',
    appId: '1:65217506040:android:aaa6c7bbeb407e3dfba90d',
    messagingSenderId: '65217506040',
    projectId: 'wateriq-cloud',
    storageBucket: 'wateriq-cloud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCre4ScqGCBEtKa_jPkLUEKEzjlLX_8VSM',
    appId: '1:65217506040:ios:36e872fe056b9305fba90d',
    messagingSenderId: '65217506040',
    projectId: 'wateriq-cloud',
    storageBucket: 'wateriq-cloud.appspot.com',
    iosBundleId: 'com.wateriqtech.wateriqcloudmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCre4ScqGCBEtKa_jPkLUEKEzjlLX_8VSM',
    appId: '1:65217506040:ios:e6e537434655a4eefba90d',
    messagingSenderId: '65217506040',
    projectId: 'wateriq-cloud',
    storageBucket: 'wateriq-cloud.appspot.com',
    iosBundleId: 'com.example.wateriqcloudMobile.RunnerTests',
  );
}
